# Generated by Django 3.2.7 on 2021-10-17 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbase',
            old_name='created',
            new_name='date_joined',
        ),
    ]
